### ISSUE TITLE
[Bug] Duplicate Categories

### ISSUE THREAD

**Issue by Lmmmmmm-bb** [xiaoluoboding/tech-stack.tools#7]
### Link / URL

https://tech-stack.tools/?category=Vue

### Description

There are duplicate Vue category.

![image](https://user-images.githubusercontent.com/54026110/194708386-d715f4d7-7603-4be8-b8aa-621208d3a47e.png)

**Comment by xiaoluoboding** [comment]
Fixed it, thanks.
